services:
  - type: web
    name: monktv-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn bot:app --host 0.0.0.0 --port 10000
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: GOOGLE_CREDS_JSON
        sync: false